### ISSUE TITLE
BUG: Transposing photo causes exception

### ISSUE THREAD

**Issue by thomas-olsson** [paolobenve/myphotoshare#46]
Hi,

There seems to be a long-standing problem that some photos cannot be transposed. In old versions (of Joachim patches to photofloat), photo is not transposed on my machine but the treewalker seem to handle the exception. This is not the case for myphotoshare / Paulo photofloat fork. 

See printouts below. Unfortunately, the photo is too big to attach... (41MB). It is a panorama from several individual photos I manual composed. 

Regards,

Thomas

```
thomas@zombie:$ identify  20160410_100829.jpg
20160410_100829.jpg JPEG 23392x1600 23392x1600+0+0 8-bit sRGB 43.26MB 0.010u 0:00.010
identify-im6.q16: Invalid SOS parameters for sequential JPEG `20160410_100829.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.

```
```
2017-08-08 14:51:22.033351   |  |  |--[ processing image/video]                      20160410_100829.jpg
Traceback (most recent call last):
  File "./main.py", line 248, in <module>
    main()
  File "./main.py", line 241, in main
    TreeWalker()
  File "/mnt/media/various/photoshare/myphotoshare/scanner/TreeWalker.py", line 29, in __init__
    [folders_album, num] = self.walk(Options.config['album_path'])
  File "/mnt/media/various/photoshare/myphotoshare/scanner/TreeWalker.py", line 168, in walk
    [next_walked_album, num] = self.walk(entry_with_path, album)
  File "/mnt/media/various/photoshare/myphotoshare/scanner/TreeWalker.py", line 210, in walk
    media = Media(album, entry_with_path, Options.config['cache_path'])
  File "/mnt/media/various/photoshare/myphotoshare/scanner/PhotoAlbum.py", line 222, in __init__
    self._photo_thumbnails(image, media_path, Options.config['cache_path'])
  File "/mnt/media/various/photoshare/myphotoshare/scanner/PhotoAlbum.py", line 369, in _photo_thumbnails
    mirror = image.transpose(Image.ROTATE_180)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1966, in transpose
    self.load()
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 244, in load
    raise_ioerror(err_code)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
IOError: broken data stream when reading image file

```

**Comment by paolobenve** [comment]
The only thing I can think of is to manage the exception and avoid the error, pushed fix in development branch,

please test it

**Comment by paolobenve** [comment]
Is this bug related to https://github.com/python-pillow/Pillow/issues/1510 ?

**Comment by thomas-olsson** [comment]
I did the same workaround locally, so at least we think alike :-). 

Tested the fix. It works as expected. 

Might be related to the bug you refer to, but I am not skilled enough to judge... seems the EOF character is 4654, not FF09, it the photo which throws the exception. However, there are other photos in my album with EOF token 4654 and with an orientation which would cause transpose the photos in myphotoshare. I have not confirmed that the transpose code is actually executed though, but reviewing the code and files make if plausible.

**Comment by paolobenve** [comment]
ok, but what does it happen with the panorama? is it shown in a weird mode?

**Comment by thomas-olsson** [comment]
I created it from multiple photos I took. I used Hugin (http://hugin.sourceforge.net/) to stich the photos together. The only weirdness is that it is extremely wide (23392x1600). The stich photo (which is the one causing the error) shows fine in any photo viewing software. With your latest patch, the photo shows up ok in myphotoshare, but upside-down, as it is not transposed. 

Attaching the resulting file from myphotoshare. 

![20160410_100829 jpg_1600](https://user-images.githubusercontent.com/17062167/29089187-bce6fa62-7c7b-11e7-9feb-6e69ec6bcb18.jpg)

**Comment by paolobenve** [comment]
ok

But will be there a way to get it correctly?

**Comment by thomas-olsson** [comment]
Googling a bit and found that "invalid SOS parameter for sequential JPEG" is not that uncommon. 

E.g. http://www.imagemagick.org/discourse-server/viewtopic.php?t=30320

Some examples for how others have addressed this:
https://github.com/owncloud/core/issues/21873
https://stackoverflow.com/questions/35337709/invalid-sos-parameters-for-sequential-jpeg

Personally, I have just this one photo with this problem. So for me, no need to fix this more than catching the exception as done in the latest patch from Paulo. However, if this is a more frequent problem, then perhaps finding a proper solution is more important.
