### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by kosli** [paolobenve/myphotoshare#53]
i get the following error with the latest version and don't know where to look at for the cause of the error? 
        58 2017-09-25 11:27:10.822554   |--[piwik_id]                                                                               [DEFAULT                                        ]
Traceback (most recent call last):
  File "/var/www/download.kos.li/private/photofloat/scanner/main.py", line 260, in <module>
    main()
  File "/var/www/download.kos.li/private/photofloat/scanner/main.py", line 252, in main
    TreeWalker()
  File "/var/www/clients/client3/web131/private/photofloat/scanner/TreeWalker.py", line 63, in __init__
    by_date_album = self.generate_date_album(origin_album)
  File "/var/www/clients/client3/web131/private/photofloat/scanner/TreeWalker.py", line 155, in generate_date_album
    self.generate_composite_image(by_date_album, by_date_max_file_date)
  File "/var/www/clients/client3/web131/private/photofloat/scanner/TreeWalker.py", line 544, in generate_composite_image
    random_thumbnails.append(random_thumbnails[i])
IndexError: list index out of range

**Comment by kosli** [comment]
have there been any changes that would need me to delete the cache and re-generate everything? :-(

**Comment by paolobenve** [comment]
no, no need to regenerate anything, only a little bug with albums with few images. Fixed in master.

Check if it's solved

**Comment by paolobenve** [comment]
no, wait, the problem should arise from something different.

Try putting a

print len(random_thumbnails)

immediately before the line

for i in range(max_thumbnail_number - len(random_thumbnails)):

I suspect that value is zero...

**Comment by kosli** [comment]
pull didn't help, and yes, the value is zero as you expected.

**Comment by paolobenve** [comment]
ok, put:

print good_media_number

immediately before line 511

while True:

and tell me the value

**Comment by paolobenve** [comment]
also: what value did you set for option max_album_share_thumbnails_number option?

what is max_thumbnail_number at line 511 ?

**Comment by kosli** [comment]
good_media_number 0
max_thumbnail_number  4
len(random_thumbnails)  0

grep max_album_share_thumbnails_number photofloat.conf
max_album_share_thumbnails_number = 16

**Comment by paolobenve** [comment]
how could we communicate more easily? whatsapp? telegram? would you send me your contact? right after we delete the comment

**Comment by paolobenve** [comment]
If I'm right, by_date_album.num_media_in_sub_tree is zero at 155. Is it zero at 153 too?

**Comment by kosli** [comment]
i've dropped you an email. thanks.
