### ISSUE TITLE
Dependency to web services must be configurable by the user

### ISSUE THREAD

**Issue by pmetras** [paolobenve/myphotoshare#60]
Hello,

To have MyPhotoShare being packaged for Debian/Ubuntu, like photofloat was, it should not depend on external web services to run. When installed, the user can decide to enable these web services, but it should not be the default. The web services should be enabled if desired in the /etc/myphotoshare/myphotoshare.conf file.

External web services:
* https://javascript-minifier.com/raw
* https://cssminifier.com/raw
* http://www.geonames.org
* openstreetmap
* googlemap
* osmtools
* Google Analytics
* Piwik

Debian provides packages of software that can replace some of these web services like cleancss

**Comment by paolobenve** [comment]
Actually I'm not satisfied with the external minifiers myphotoshare is using, they often go in time out mode and return an error message without the possibility to detect it, getting rid of them is welcome, but I don't master cleancss!

For the rest, it seems quite simple

**Comment by paolobenve** [comment]
Google Analytics and Piwik integration is already not activated.

**Comment by paolobenve** [comment]
geotags are now excluded by default in master

**Comment by pmetras** [comment]
I should push a pull request to use local minifiers or web services soon, when I solve the git mess on my server...

**Comment by paolobenve** [comment]
thank you!!!

**Comment by paolobenve** [comment]
Now we are using an option in config file in order to decide how to minify, but this option is used only by the minifier script.

What about giving the script a simple parameter specifying the method to use? the script itself would be more simple, would avoid to read files, and the config file would be cleaner

**Comment by pmetras** [comment]
Effectively. As the minifier script is run only once, there's no strong argument at storing the minifiers used. On the reverse, keeping all options in a single place can make it simpler to understand how the minfied files were produced when a bug is found in a minified CSS or Javascript.

My initial goal was if MyPhotoShare is bundled for a linux distribution, it should not call external web services without the user knowing it when the package is installed. So the default minifiers should be local packages or no minification; web services are not an option. But if the packager decide to use minifiers with local packages, he should make these packages dependencies of MyPhotoshare. And the final user should be able to change these values after the installation if he will. It means that the final user must know what minifiers were used during the MyPhotoshare package installation. It can be explained in the package documentation (simpler; that's what you suggest and that can be enough) or in a config file (what I did).

Both arguments hold and you can decide which one you prefer.

**Comment by paolobenve** [comment]
Let's let it as it is. Thank you!

Closing
