### ISSUE TITLE
Can't watch videos in firefox

### ISSUE THREAD

**Issue by pmetras** [paolobenve/myphotoshare#65]
I've added videos to my test album and I can't watch them. Whenever MyPhotoShare displays a photo or a video, the mouse cursor turns to **<=>**. In the case of a video, it remains as **<=>** when moved over the browser video player, and changes for the traditional mouse pointer over the video controls. But when I click on the play button, the click is interpreted as a change media request and it displays the next photo or video instead of playing the current video.

This happens with FireFox 57.0.4 (64-bit).

**Comment by paolobenve** [comment]
yes, confirmed in firefox, while not in chromium and vivaldi

shift-click is required in firefox

perhaps a propagation problem?

**Comment by paolobenve** [comment]
merged, closing

**Comment by paolobenve** [comment]
corrected cursor on video
